from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

def save_result_pdf(username, fracture_type, result_status, filename="fracture_report.pdf"):
    c = canvas.Canvas("fracture_report_darshan.pdf", pagesize=letter)

    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(100, height - 80, "Deep Bone Fracture Detection Report")

    # Patient details
    c.setFont("Helvetica", 12)
    c.drawString(100, height - 150, f"Patient/User: {username}")
    c.drawString(100, height - 180, f"Type of Bone: {fracture_type}")

    # Result
    if result_status.lower() == "fractured":
        c.setFillColorRGB(1, 0, 0)   # Red
    else:
        c.setFillColorRGB(0, 0.5, 0) # Green
    c.drawString(100, height - 210, f"Result: {result_status}")
    c.setFillColorRGB(0, 0, 0)  # Reset color

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(100, 100, "Generated by Deep Bone Fracture Detection System")

    c.save()
    print(f"✅ PDF saved as {filename}")

# Test run
save_result_pdf("Darshan", "Hand", "Normal")
